name: First Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello KR2- Pipeline Running!"
